//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISC.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ISC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 DockView 的本地化字符串。
        /// </summary>
        internal static string DockView {
            get {
                return ResourceManager.GetString("DockView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FileControlTemplate_List 的本地化字符串。
        /// </summary>
        internal static string FileControlTemplate_List {
            get {
                return ResourceManager.GetString("FileControlTemplate_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FileControlTemplate_Tile 的本地化字符串。
        /// </summary>
        internal static string FileControlTemplate_Tile {
            get {
                return ResourceManager.GetString("FileControlTemplate_Tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FileDataTemplate_List 的本地化字符串。
        /// </summary>
        internal static string FileDataTemplate_List {
            get {
                return ResourceManager.GetString("FileDataTemplate_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FileDataTemplate_Thumbnail 的本地化字符串。
        /// </summary>
        internal static string FileDataTemplate_Thumbnail {
            get {
                return ResourceManager.GetString("FileDataTemplate_Thumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FileDataTemplate_Tile 的本地化字符串。
        /// </summary>
        internal static string FileDataTemplate_Tile {
            get {
                return ResourceManager.GetString("FileDataTemplate_Tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FilePane 的本地化字符串。
        /// </summary>
        internal static string FilePane {
            get {
                return ResourceManager.GetString("FilePane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}\\Global\\File 的本地化字符串。
        /// </summary>
        internal static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I_Open 的本地化字符串。
        /// </summary>
        internal static string I_Open {
            get {
                return ResourceManager.GetString("I_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}\\Global\\Resource\\Icons\\{1}.ico 的本地化字符串。
        /// </summary>
        internal static string IconPath {
            get {
                return ResourceManager.GetString("IconPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /ISC;component/Global/Dictionary/Language/{0}.xaml 的本地化字符串。
        /// </summary>
        internal static string LanguageFilePath {
            get {
                return ResourceManager.GetString("LanguageFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LogOnOffView 的本地化字符串。
        /// </summary>
        internal static string LogOnOffView {
            get {
                return ResourceManager.GetString("LogOnOffView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NetworkPane 的本地化字符串。
        /// </summary>
        internal static string NetworkPane {
            get {
                return ResourceManager.GetString("NetworkPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ISC.View.Popups 的本地化字符串。
        /// </summary>
        internal static string PopupWindowPath {
            get {
                return ResourceManager.GetString("PopupWindowPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RecordPlaybackOptionsView 的本地化字符串。
        /// </summary>
        internal static string RecordPlaybackOptionsView {
            get {
                return ResourceManager.GetString("RecordPlaybackOptionsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SelectionPane 的本地化字符串。
        /// </summary>
        internal static string SelectionPane {
            get {
                return ResourceManager.GetString("SelectionPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap SplashScreen {
            get {
                object obj = ResourceManager.GetObject("SplashScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 StepView 的本地化字符串。
        /// </summary>
        internal static string StepView {
            get {
                return ResourceManager.GetString("StepView", resourceCulture);
            }
        }
    }
}
